### PR TITLE
Implemented Websockets Connection

### PR DESCRIPTION
**Pull request by silicon-ninja**
Used Websockets and created their endpoints and made a DB connection 
Still having an error with DB connecting will resolve it by tomorrow

### CODE REVIEW

**Comment by firekind** [comment]
Ok a couple of things:
- Add tons of comments, especially in the websocket parts. I have no clue how websockets work in springboot, so you guys have to write the comments in such a way that a layman can figure out what does what and why so and so things are needed. Future maintainers of this code will benefit from this as well.
- Did you test this out? 
    - looking at the code, it seems to me that it will work only for one channel. Each topic is a channel right? But you have hard coded the `SendTo` arguments.
- I dont see any of the mongo connection code.

With regards to formatting,
- Keep a consistent name style. Class names in camel case with first letter capital. regular variables camel case. It does a lot to enhance readability.

**Comment by silicon-ninja** [comment]
Sure I will make the changes and ..yes mongoDB is up and running in DBInfo folder

**Comment by silicon-ninja** [comment]
Fixed and Updated all the issues with my last PR @firekind

**Comment by firekind** [comment]
The stuff we talked about yesterday isn't there (the `@Document` thingy and you renamed `schema` class to `Messaging` remember?) 

And for the love of god, please format your code files.

**Comment by silicon-ninja** [comment]
> The stuff we talked about yesterday isn't there (the `@Document` thingy and you renamed `schema` class to `Messaging` remember?)
> 
> And for the love of God, please format your code files.

Reply {
Yeah I will re-submit the PR by Today sorry for the delay 
and yeah I will definitely format the code structure 😅😂
}

**Pull request closed without merging**
